// TASK 4 — STRUCT DUMP: turns the 187-unread-structs problem into a readable
// document. For every authored struct, generate 2 items (different seeds) and
// emit prompt verbatim, options verbatim, marked answer, renderCapacity,
// and an unchecked read box. No browser, no UI, no session state.
//
// Output: reports/struct-audit.md (commit; humans tick boxes in later commits)
import { writeFileSync, mkdirSync } from "fs";
import { execSync } from "child_process";
import { GENERATORS } from "/opt/data/projects/multicheck/lib/questions.ts";

function h(seed) {
  let s = seed >>> 0;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 4294967296;
  };
}

// renderCapacity: DISTINCT contents a struct can emit (prompt + sorted options),
// probed over many seeds at fixed structIndex — same identity the memwindow fix uses.
function measureCapacity(gen, si, seeds = 1500) {
  const seen = new Set();
  for (let i = 0; i < seeds; i++) {
    const q = gen(h((i + 1) * 2654435761 % 2147483647), 50, si);
    if (!q) continue;
    seen.add(q.prompt + "|" + (q.options ? [...q.options].sort().join("¦") : q.answer));
  }
  return seen.size;
}

const sha = (() => { try { return execSync("git rev-parse --short HEAD", { cwd: "/opt/data/projects/multicheck" }).toString().trim(); } catch { return "unknown"; } })();

const entries = [];
for (const [subskill, gens] of Object.entries(GENERATORS)) {
  for (let si = 0; si < gens.length; si++) {
    const samples = [];
    for (let k = 0; k < 2; k++) {
      const r = h(1000003 * (si + 1) + k * 7919);
      const q = gens[si](r, 50, si);
      samples.push(q ? { prompt: q.prompt, stimulus: q.stimulus, options: q.options, answer: q.answer } : null);
    }
    entries.push({ subskill, si, samples, capacity: measureCapacity(gens[si], si) });
  }
}

const L = [];
L.push("# STRUCT AUDIT — multicheck question generators");
L.push("");
L.push(`Generated by scripts/dump-structs.mjs @ ${sha} · ${new Date().toISOString().slice(0, 10)}`);
L.push("");
L.push("Two samples per struct, different seeds. Read BOTH before ticking.");
L.push("Known defect classes: two defensible answers · unjustified answer · dead code (computed-then-discarded) · brittle ternary answer selection · ungrammatical/typo.");
L.push("");

for (const sub of [...new Set(entries.map((e) => e.subskill))]) {
  const es = entries.filter((e) => e.subskill === sub);
  L.push(`## ${sub} (${es.length} structs)`);
  L.push("");
  for (const e of es) {
    L.push(`### [${e.subskill}:${e.si}]  renderCapacity ≈ **${e.capacity}** distinct contents`);
    L.push("");
    e.samples.forEach((q, k) => {
      if (!q) { L.push(`**Sample ${k + 1}:** generator returned null`); L.push(""); return; }
      L.push(`**Sample ${k + 1}**`);
      L.push(`> PROMPT: ${q.prompt.replace(/\n/g, " ")}`);
      if (q.stimulus) {
        const t = q.stimulus.length > 200 ? q.stimulus.slice(0, 200) + "…" : q.stimulus;
        L.push(`> STIMULUS (trunc): ${t.replace(/\n/g, " ")}`);
      }
      if (q.options?.length) {
        L.push(`> OPTIONS:`);
        q.options.forEach((o, ix) => L.push(`>   ${ix + 1}) ${o}${o === q.answer ? " ✅" : ""}`));
      } else {
        L.push(`> ANSWER: ${q.answer}`);
      }
      L.push("");
    });
    L.push(`- [ ] both samples read — initials/date:`);
    L.push(`- [ ] defect? class + root cause (blank if clean):`);
    L.push("");
  }
}

L.push("---");
L.push(`TOTAL STRUCTS: ${entries.length}`);
L.push(`READ SO FAR: 22 / ${entries.length} (prozesslogik complete from earlier sessions). Update this line as you read.`);
mkdirSync("/opt/data/projects/multicheck/reports", { recursive: true });
writeFileSync("/opt/data/projects/multicheck/reports/struct-audit.md", L.join("\n"));
console.log(`struct-audit.md written: ${entries.length} structs across ${new Set(entries.map(e => e.subskill)).size} subskills`);
